#!/usr/bin/python
#
# (c) Copyright 2009 Cloudera, Inc.
#

# Default target: build a package distribution for metamake
metamake = PythonRedistTarget(
  package_name = "metamake",
  version = ":version",
  use_dist_utils = True,
  steps = [
    # Copy files into assembly directory
    CopyDir(src_dir="src", dest_dir="$/"),
    CopyDir(src_dir="etc", dest_dir="$/etc"),
    CopyDir(src_dir="lib", dest_dir="$/lib"),
    CopyFile(src_file="%(srcdir)/bin/metamake", dest_dir="$/bin"),

    # Mark non-python-source files that need to be packaged
    AddDistUtilsDataFile("bin/metamake", "/usr/bin/"),
    AddDistUtilsDataDir("etc/", "/etc/metamake"),
    AddDistUtilsDataDir("lib/", "/usr/lib/metamake"),
  ])


# Target defining the version number for metamake
version = VerStringTarget(version = "0.1.0")


# To execute unit tests, run './build :test' or './build --phase test' 
test = PythonTestTarget(
  sources = ["src/metamake/" ],
  main_module = "metamake.alltests")

# virtual target to define nested targets
ProjectList(required_targets=[
  "TestTargets"])

