#!/usr/bin/python
#
# (c) Copyright 2009 Cloudera, Inc.
#

# Default target: build a package distribution for metamake
metamake = PythonRedistTarget(
  package_name = "metamake",
  required_targets = [ ":src" ],
  version = ":version",
  use_dist_utils = True,
  steps = [
    # Mark non-python-source files that need to be packaged
    AddDistUtilsDataDir("%(srcdir)/etc", "/etc/metamake"),
    AddDistUtilsDataDir("%(srcdir)/lib", "/usr/lib/metamake"),
    AddDistUtilsDataFile("%(srcdir)/bin/metamake", "/usr/bin/"),
  ])


# Target defining the version number for metamake
version = VerStringTarget(version = "0.1.0")

# Target describing all python sources used by metamake
src = PythonTarget(
  sources = ["src/metamake",
             "src/makeJava.py",
             "src/checkmanifest",
             "src/copyPy.py",
             "src/makePy.py",
             "src/makeSetup.py",
             "src/makeVer.py",
             "src/metamake/"])

# To execute unit tests, run './build :test' or './build --phase test' 
test = PythonTestTarget(
  sources = ["src/metamakelib" ],
  main_module = "metamakelib.alltests")

# virtual target to define nested targets
ProjectList(required_targets=[
  "TestTargets"])

